--
-- Current Database: `employees`
--

CREATE DATABASE /*!32312 IF NOT EXISTS*/ `employees` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `employees`;

--
-- Table structure for table `EMPLOYEES`
--

DROP TABLE IF EXISTS `EMPLOYEES`;
CREATE TABLE `EMPLOYEES` (
  `EMPLOYEE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_NAME` varchar(35) NOT NULL,
  PRIMARY KEY (`EMPLOYEE_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;

LOCK TABLES `EMPLOYEES` WRITE;

UNLOCK TABLES;

INSERT INTO EMPLOYEES (EMPLOYEE_NAME) VALUES ("Jesus Maria Garcia");
INSERT INTO EMPLOYEES (EMPLOYEE_NAME) VALUES ("April Halden");
INSERT INTO EMPLOYEES (EMPLOYEE_NAME) VALUES ("Eric Abbruzzese");
INSERT INTO EMPLOYEES (EMPLOYEE_NAME) VALUES ("Kai Pak");
INSERT INTO EMPLOYEES (EMPLOYEE_NAME) VALUES ("Grace Andrews");
